services:
  - type: web
    name: haryanasarthi
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: REDIS_URL
        value: ""
